"""Frozen research contracts and design locks."""

from qlib_platform.research.contracts.ashare_etf import (
    ETF_FORBIDDEN_STOCK_DATASETS,
    ETF_REQUIRED_DATASETS,
    EtfTradabilityObservation,
    EtfUniverseMember,
    EtfUniversePolicy,
    EtfUniverseSelection,
    assert_etf_data_contract,
    select_ashare_etf_universe,
)
from qlib_platform.research.contracts.research_profile import (
    DEFAULT_RESEARCH_PROFILE_ID,
    RESEARCH_PROFILES,
    CalendarVersion,
    InstrumentSpec,
    LabelDefinition,
    ResearchProfile,
    SymbolAlias,
    ashare_etf_instrument,
    assert_information_available,
    describe_research_profile,
    legacy_ashare_instrument,
    require_research_profile,
    research_profile_from_settings,
)

__all__ = [
    "DEFAULT_RESEARCH_PROFILE_ID",
    "ETF_FORBIDDEN_STOCK_DATASETS",
    "ETF_REQUIRED_DATASETS",
    "RESEARCH_PROFILES",
    "CalendarVersion",
    "EtfTradabilityObservation",
    "EtfUniverseMember",
    "EtfUniversePolicy",
    "EtfUniverseSelection",
    "InstrumentSpec",
    "LabelDefinition",
    "ResearchProfile",
    "SymbolAlias",
    "ashare_etf_instrument",
    "assert_etf_data_contract",
    "assert_information_available",
    "describe_research_profile",
    "legacy_ashare_instrument",
    "require_research_profile",
    "research_profile_from_settings",
    "select_ashare_etf_universe",
]
