"""Register CLI commands owned by the data domain."""

import argparse


def register(sub) -> None:
    sub.add_parser("init-metadata")
    b = sub.add_parser("backfill")
    b.add_argument("--start")
    b.add_argument("--end")
    b.add_argument("--force", action="store_true")
    extended = sub.add_parser("backfill-extended")
    extended.add_argument("--start")
    extended.add_argument("--end")
    extended.add_argument("--groups", nargs="+", help="data domains; defaults to all extended domains")
    extended.add_argument("--force", action="store_true")
    extended.add_argument("--workers", type=int, help="parallel workers for per-symbol history endpoints")
    sp = sub.add_parser("source-preflight")
    sp.add_argument("--start")
    sp.add_argument("--end")
    sb = sub.add_parser("sync-benchmark")
    sb.add_argument("--symbol", default="SH000300")
    sb.add_argument("--start")
    sb.add_argument("--end")
    su_members = sub.add_parser("sync-universe")
    su_members.add_argument("--start")
    su_members.add_argument("--end")
    sync_industry = sub.add_parser("sync-industry")
    sync_industry.add_argument("--end", required=True)
    daily_sync = sub.add_parser("daily-sync")
    daily_sync.add_argument("--as-of")
    daily_sync.add_argument("--check-only", action="store_true")
    daily_sync.add_argument("--force-full", action="store_true")
    dividends = sub.add_parser("sync-dividends")
    dividends.add_argument("--bootstrap", action="store_true")
    dividends.add_argument("--resume", action=argparse.BooleanOptionalAction, default=True)
    kline = sub.add_parser("export-kline")
    kline.add_argument("--symbol", required=True)
    kline.add_argument("--adjust", choices=["raw", "qfq", "hfq"], default="raw")
    kline.add_argument("--start")
    kline.add_argument("--end")
    kline.add_argument("--output", required=True)
    c = sub.add_parser("curate")
    c.add_argument("--start")
    c.add_argument("--end")
    d = sub.add_parser("curate-day")
    d.add_argument("trade_date")
    d.add_argument("--force", action="store_true")
    sf = sub.add_parser("stage-full")
    sf.add_argument("--force", action="store_true")
    df = sub.add_parser("dump-full")
    df.add_argument("--single-thread", action="store_true")
    su = sub.add_parser("stage-update")
    su.add_argument("trade_dates", nargs="+")
    du = sub.add_parser("dump-update")
    du.add_argument("--single-thread", action="store_true")
    fi = sub.add_parser("ingest-pit-fundamentals")
    fi.add_argument("reports")
    fi.add_argument("--calendar")
    fi.add_argument("--output")
    bootstrap_cmd = sub.add_parser("bootstrap")
    bootstrap_cmd.add_argument("--source", choices=["auto", "qlib", "raw", "tushare"], default="auto")
    bootstrap_cmd.add_argument("--path")
    bootstrap_cmd.add_argument("--start")
    bootstrap_cmd.add_argument("--end")
    migration_acceptance = sub.add_parser("migration-acceptance")
    migration_acceptance.add_argument("--source", choices=["qlib", "research"], required=True)
    migration_acceptance.add_argument("--source-root", required=True)
    migration_acceptance.add_argument("--acceptance-root", required=True)
    migration_acceptance.add_argument("--start")
    migration_acceptance.add_argument("--end")
    migration_acceptance.add_argument("--single-thread", action="store_true")
