"""Register CLI commands owned by the runtime domain."""


def register(sub) -> None:
    runtime_probe = sub.add_parser("runtime-probe")
    runtime_probe.add_argument("--model-profile", required=True)
    model_refit = sub.add_parser("model-refit")
    model_refit.add_argument("--research-run", required=True)
    model_refit.add_argument("--as-of", required=True)
    model_deploy = sub.add_parser("model-deploy")
    model_deploy.add_argument("deployment_id")
    model_deploy.add_argument("--device", default="cpu")
    model_rollback = sub.add_parser("model-rollback")
    model_rollback.add_argument("--to", required=True, dest="deployment_id")
    model_rollback.add_argument("--device", default="cpu")
    sub.add_parser("model-status")
    status = sub.add_parser("status")
    status.add_argument("--json", action="store_true", dest="as_json")
    health = sub.add_parser("health")
    health.add_argument("kind", choices=["live", "ready", "dependencies"])
    live = sub.add_parser("live-inference")
    live.add_argument("--as-of", required=True)
    live.add_argument("--deployment-id")
    live.add_argument("--require-daily-sync", action="store_true")
    live.add_argument("--supersede", action="store_true")
    live.add_argument("--dataset-uri")
    live.add_argument("--dataset-ref")
    live.add_argument("--compare-research")
    live.add_argument("--parity-output")
    daily_signal = sub.add_parser("daily-signal-run")
    daily_signal.add_argument("--as-of", required=True)
    daily_signal.add_argument("--no-notify", action="store_true")
    daily_signal.add_argument("--skip-sync", action="store_true")
    daily_signal.add_argument("--supersede", action="store_true")
