name: qlib_lstm_v1
family: qlib_lstm
device: auto
device_index: 0
model_kwargs:
  step_len: 20
  hidden_size: 64
  num_layers: 2
  dropout: 0.0
  n_epochs: 100
  lr: 0.001
  early_stop: 10
  batch_size: 800
  metric: loss
  loss: mse
