name: xgboost_cpu_v1
family: xgboost
device: cpu
device_index: 0
model_kwargs:
  objective: reg:squarederror
  eta: 0.03
  max_depth: 8
  subsample: 0.8
  colsample_bytree: 0.8
  num_boost_round: 2000
  early_stopping_rounds: 100
